<<<<<<< Updated upstream
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Roblox', 2006, 'Jogo de simulação', 'Roblox Corporation ', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Silent Hill', 1999, 'Survival Horror', 'Konami, Team silent',TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Five nights at Freddy', 2014 , 'Survivor Horror', 'Scott Cawthon', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Outlast', 2013 , 'Survivor Horror', 'Red Barrels Studio', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Dress to Impress', 2024, 'Interpretação de papéis e simulador de avatar', 'Dress to Impress Group', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Subway Surfers', 2012, 'Jogo de Corrida', 'SYBO Games', False)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Slither.io', 2016, 'Jogo multijogador massivo online', 'Steve Howse', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Slender', 2013, 'Survivor Horror', 'Blue Isle Studio', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('POU', 2012, 'Animal de estimação virtual', 'Paul Salameh', FALSE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('My Talking Tom', 2013, 'Animal de estimação virtual', 'Outfit 7', FALSE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('My Talking Angela', 2014, 'Animal de estimação virtual', 'Outfit 7', FALSE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('The Forest', 2014, 'Survivor Horror', 'Endnight Games Limited', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('UNO Online', 2021, 'Jogo de cartas', 'Wobin', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Candy Crush', 2012, 'Jogo Eletrônico de quebra cabeça', 'KING', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Brawl Stars', 2017, 'Jogo Eletrônico de Tiro', 'Supercell',TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Resident Evil', 2002, 'Survivor Horror', 'Capcom', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Resident Evil 2', 2019, 'Survivor Horror', 'Capcom', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Resident Evil 3', 2020, 'Survivor Horror', 'Capcom', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Resident Evil 4', 2023, 'Survivor Horror', 'Capcom', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Bedwars', 2018, 'Jogo eletrônico de tiro', 'Blockman Go', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Dead Silence', 2011, 'Survivor Horror', 'DoomX10', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Among Us', 2018, 'Jogo eletrônico de sobrevivência', 'InnerSlot', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Adopt me', 2017, 'Interpretação de papéis e simulador de avatar', 'Upflit Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Murder Mistery 2', 2014, 'Sobrevivência', 'Nikilis',TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Flee the facility', 2017, 'Sobrevivência', 'A.W Apps', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Rocitizens', 2013, 'Interpretação de papéis simulador de avatar', 'FireBrand1', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Gartic', 2008, 'Jogo online', 'Gartic Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Foxhole', 2016, 'Jogo multijogador massivo online', 'Siege Camp', FALSE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Habbo Hotel', 2000, ' Simulador de vida', 'Sulake', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Club Penguin', 2005, 'MMORPG', 'Disney Canada Inc', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('North Garden', 2017, 'Estratégia em tempo real', 'Shiro Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Town of Salem', 2014, 'Jogo eletrônico de estratégia', 'BlankMediaGames', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Spellbreak', 2020, 'Role-playing game', ' Proletariat, Inc', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fallen London', 2009, 'Jogo eletrônico de aventura', ' Failbetter Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('KurtzPel', 2019, ' Jogo eletrônico de luta', 'KOG Studios', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Bus Simulator', 2021, 'Simulador de Veículo', 'MiniDavid29', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Simulador de linha de banheiro', 2024, 'Simulação', 'Snow Moose Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Doors', 2021, 'Sobrevivência', 'LSPLAHS', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Capybara Limpeza Tycoon', 2024, 'Simulação', 'Dynabyte Studios', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Bar do Bira', 2024, 'Simulação', 'ReyReno777', TRUE)


*teste*
=======
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('', , '', '', )
>>>>>>> Stashed changes
