INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Slime Rancher', 2017, 'Aventura/Sandbox', 'Monomi Park', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fae Farm', 2023, 'Simulação/RPG', 'Phoenix Labs', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Rising Storm 2: Vietnam',  2017, 'Tiro em primeira pessoa', 'Antimatter Games/Tripwire Interactive', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Deep Rock Galactic',  2020, 'Ação Cooperativa', 'Ghost Ship Games','PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Albion Online', 2017, 'MMORPG', 'Sandbox Interactive GmbH','PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Unturned', 2014, 'Sobrevivência/Sandbox', 'Smartly Dressed Games',  'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Worms W.M.D', 2016, 'Estratégia/Turno a Turno', 'Team17 Digital Ltd.', 'PS4', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Brawlhalla', 2017, 'Luta/Plataforma', 'Blue Mammoth Games', 'Xbox One', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('The Cycle: Frontier', 2022, 'FPS/Competição PvPvE', 'YAGER Development GmbH', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Cook Serve Delicious! 3?!', 2020, 'Simulação/Tycoon/Cozinha', 'Vertigo Gaming Inc.', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('SpellForce 3: Soul Harvest', 2019, 'RPG/RTS', 'Grimlore Games', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Totally Accurate Battle Simulator', 2021, 'Estratégia/Simulações', 'Landfall Games', 'PC',FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Valhall', 2022, 'Ação/Aventura', 'M2H', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Mordhau', 2019, 'Ação/Multi-jogador', 'Torn Banner Studios', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Surgeon Simulator 2' , 2020, 'Simulação/Comédia', 'Bossa Studios', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Hyper Scape' , 2020, 'Battle Royale/FPS', 'bisoft Montreal', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('No More Room in Hell' , 2013,'Survival Horror/Tiro em primeira pessoa', 'No More Room in Hell Team', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Insurgency: Sandstorm' , 2018, 'Tiro em primeira pessoa/Simulação militar', 'New World Interactive', 'PC', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Swords of Legends Online' , 2021 , 'MMORPG/Ação/RPG', 'Wangyuan Shengtang & Aurogon Shanghai & Gameforge AG' ,'PC',FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Phantom Forces' , 2015, 'FPS/Multiplayer online shooter' , 'StyLiS Studios' , 'Roblox', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Realm Royale' , 2018, 'Battle Royale/Fantasia' , 'Heroic Leap Games' , 'PC', FALSE)  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Avatar: Reckoning' , 2023 , 'FPS/Ação/Aventura', 'Archosaur Games' , 'Multiplataforma Mobile',FALSE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Dying Light: Bad Blood ', 2018 , 'Ação/Sobrevivência/Battle Royale' ,'Techland', 'Multiplataforma', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Warframe' , 2013 , 'Ação/RPG/Gratuito' , 'Digital Extremes' , 'Multiplataforma', TRUE)  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Scavengers ', 2022 , 'Ação/Sobrevivência/PvPvE', 'Midwinter Entertainment' , 'Multiplataforma', TRUE)  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Satisfactory' , 2020 , 'Construção/Sobrevivência' , 'Coffee Stain Studios' ,'Multiplataforma',TRUE)  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Astroneer' , 2019 ,'Sandbox/Aventura/Exploração' , 'System Era Softworks' , 'Multiplataforma',TRUE)  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('World War 3' , 2022 , 'Tiro em primeira pessoa/Multiplayer', 'The Farm 51' , 'Multiplataforma',TRUE )  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Phasmophobia' , 2020 ,'Horror/Sobrevivência/Cooperação' , 'Kinetic Games' , 'Multiplataforma', TRUE )  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fall Guys: Ultimate Knockout' , 2020 , 'Party Game/Competição Online' , 'Mediatonic' , 'Multiplataforma',TRUE )  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Dead by Daylight' , 2016 , 'Terror/Multi-jogador Online de Sobrevivência' , 'Behaviour Interactive' , 'Multiplataforma',TRUE )  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Project Zomboid' , 2013 , 'Aventura/Sobrevivência/Zumbis', 'The Indie Stone', 'PC', FALSE)  
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Totally Accurate Battle Simulator' , 2021 , 'Estratégia/Simulações/Luta' , 'Landfall Games' ,'PC', FALSE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Warframe'  'MMORPG/Ação/RPG', 2013,  'Digital Extremes',  'Multi-plataforma', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Hunt: Showdown'  'FPS/PvPvE', 2018,   'Crytek',   'Multi-plataforma',TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Paladins ' , 'MOBA/FPS', 2016 ,  'Hi-Rez Studios' ,  'Multi-plataforma',TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('TerraTech' , 2015,  'Sandbox/Aventura' ,  'Payload Studios'  , 'Multi-plataforma',TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Crusader Kings III' , 2020, 'RPG/Estratégia' ,  'Paradox Interactive'  , 'Multi-plataforma', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('EVE Online'  'MMORPG/Espaço', 2003, 'CCP Games',  'Multi-plataforma', TRUE )
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('ARK: Survival Evolved' , 2015, 'Sobrevivência/Sandbox' ,  'Studio Wildcard' , 'Multi-plataforma', TRUE)