
INSERT INTO jogos_antigos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma)
VALUES 
('Super Mario Bros', 1985, 'Plataforma', 'Nintendo', TRUE),
('The Legend of Zelda: Tears of the Kingdom', 1986, 'Ação-aventura', 'Nintendo', TRUE),
('Pac-Man', 1980, 'Arcade', 'Namco', FALSE),
('Street Fighter II', 1991, 'Luta', 'Capcom', TRUE),
('Sonic the Hedgehog', 1991, 'Plataforma', 'Sega', TRUE),
('Donkey Kong', 1981, 'Arcade', 'Nintendo', FALSE),
('Tetris', 1984, 'Puzzle', 'Alexey Pajitnov', TRUE),
('Mega Man', 1987, 'Ação', 'Capcom', TRUE),
('Final Fantasy', 1987, 'RPG', 'Square', TRUE),
('Dragon Quest', 1986, 'RPG', 'Enix', TRUE),
('Mortal Kombat', 1992, 'Luta', 'Midway', TRUE),
('Castlevania', 1986, 'Ação-plataforma', 'Konami', TRUE),
('Metroid', 1986, 'Ação-aventura', 'Nintendo', TRUE),
('Contra', 1987, 'Tiro', 'Konami', TRUE),
('Prince of Persia', 1989, 'Ação-plataforma', 'Brøderbund', TRUE),
('Double Dragon', 1987, 'Luta', 'Technos Japan', TRUE),
('Doom', 1993, 'Tiro em primeira pessoa', 'id Software', TRUE),
('Wolfenstein 3D', 1992, 'Tiro em primeira pessoa', 'id Software', TRUE),
('The Oregon Trail', 1971, 'Simulação', 'MECC', FALSE),
('Space Invaders', 1978, 'Arcade', 'Taito', FALSE),
('Galaga', 1981, 'Arcade', 'Namco', FALSE),
('Asteroids', 1979, 'Arcade', 'Atari', FALSE),
('Pong', 1972, 'Esporte', 'Atari', FALSE),
('Zork', 1980, 'Aventura de texto', 'Infocom', FALSE),
('Q*bert', 1982, 'Arcade', 'Gottlieb', FALSE),
('Bomberman', 1983, 'Puzzle', 'Hudson Soft', TRUE),
('Frogger', 1981, 'Arcade', 'Konami', TRUE),
('Dig Dug', 1982, 'Arcade', 'Namco', FALSE),
('Pitfall!', 1982, 'Plataforma', 'Activision', FALSE),
('The Sims', 2000, 'Simulação', 'Maxis', TRUE),
('Civilization', 1991, 'Estratégia', 'MicroProse', TRUE),
('Command & Conquer', 1995, 'Estratégia', 'Westwood Studios', TRUE),
('Warcraft: Orcs & Humans', 1994, 'Estratégia', 'Blizzard Entertainment', TRUE),
('SimCity', 1989, 'Simulação', 'Maxis', TRUE),
('Alone in the Dark', 1992, 'Survival Horror', 'Infogrames', TRUE),
('StarCraft', 1998, 'Estratégia', 'Blizzard Entertainment', TRUE),
('Diablo', 1996, 'RPG', 'Blizzard Entertainment', TRUE),
('GoldenEye 007', 1997, 'Tiro em primeira pessoa', 'Rare', TRUE),
('Half-Life', 1998, 'Tiro em primeira pessoa', 'Valve', TRUE);
