INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Free Fire', 2017, 'Battle Royale', 'Garena', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fortnite', 2017, 'Battle Royale', 'Epic Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('The Legend of Zelda', 1986, 'Ação-aventura', 'Nintendo', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Valorant', 2020, 'FPS tático', 'Riot Games', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Counter Strike', 2000, 'FPS tático', 'Valve Corporation', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Stumble Guys', 2020, 'Battle Royale', 'Kitka Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Battlefield V', 2018, 'FPS tático', 'Dice', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fall Guys', 2020, 'Multiplayer', 'Mediatonic', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('God of War Ragnarok', 2022, 'Corrida', 'Pollyphone Digital', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Among Us', 2018, 'Multiplayer', 'Innersloth', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Super Mario Odyssey', 2017, 'Plataforma', 'Nintendo', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Overwatch', 2016, 'FPS tático', 'Blizzard Entertainmeint', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Apex Legend', 2019, 'Battle Royale', 'Respawn Entertainment', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Far Cry 5', 2018, 'Ação', 'Ubisoft', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('The Sims 4', 2014, 'Simulação', 'Maxis', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Rocket League', 2015, 'Esportes', 'Psyonix', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('The Last Guardian', 2016, 'Aventura', 'Japan Studio', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Guitar Hero', 2015, 'Música', 'FreeeStyleGames', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Resident Evil Village', 2021, 'Terror', 'Capcom', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Gran Turismo 7', 2022, 'Corrida', 'Polyphone Digital', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fifa 21', 2020, 'Esportes', 'EA Sports', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('NBA 2K21', 2020, 'Esportes', 'Visual Concepts', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Nioh 2', 2020, 'RPG', 'Team Ninja', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Cuphead', 2017, 'Plataforma', 'Studio MDHR', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Ghost Recon: Breakpoint', 2019, 'FPS', 'Ubisoft', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Assassin s Creed Odyssey', 2018, 'Ação', 'Ubisoft', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Fallout 4', 2015, 'RPG', 'Bethesda Game Studio', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('League of Legends', 2009, 'MOBA', 'Riot Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Just Dance 2021', 2020, 'Música', 'Ubisoft', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Mario Kart 8 Deluxe', 2017, 'Corrida', 'Nintendo', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Final Fantasy XV', 2016, 'RPG', 'Square Enix', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Celeste', 2018, 'Plataforma', 'Maddy Makes Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Hollow Knight', 2017, 'Aventura', 'Team Cherry', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Monster Hunter: World', 2018, 'RPG', 'Capcom', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Minecraft', 2011, 'Sandbox', 'Mojang', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Red Dead Redemption 2', 2018, 'Ação', 'Rockstar Games', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('GTA V', 2013, 'Mundo Aberto', 'Rockstar Games', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Ghost of Tsushima', 2020, 'Ação', 'Sucker Punch Productions', FALSE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Ghostrunner', 2020, 'Ação', 'One More Level', TRUE)
INSERT INTO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Hitman 3', 2021, 'Ação', 'IO Interactive', TRUE)