INSERT TO jogos (nome, ano_publicacao, genero, desenvolvedor, multi_plataforma) VALUES ('Crash Bandicoot 4: Its About Time Standard Edition Activision', 2020, 'Ação', 'Toys for Bob', TRUE),
('Crash Bandicoot: N. Sane Trilogy N. Sane Trilogy Standard Edition Activision', 2017, 'Ação', 'Vicarious Visions', TRUE),
('Crash Team Rumble Deluxe Edition', 2023, 'Ação', 'Vicarious Visions', TRUE),
('Fortune Rabbit', 2021, 'Aposta', 'PG', FALSE),
('Fortune Tiger', 2021, 'Aposta', 'PG', FALSE),
('Fortune Ox', 2021, 'Aposta', 'PG', FALSE),
('Fortune Dragon', 2021, 'Aposta', 'PG', FALSE),
('Black Jack', 2020, 'Aposta', 'Pragmatic', FALSE),
('Baccarat', 2020, 'Aposta', 'Pragmatic', FALSE),
('Fortune Gems', 2022, 'Aposta', 'PG', FALSE),
('Gates of Olympus', 2022, 'Aposta', 'PG', FALSE),
('Crash', 2019, 'Aposta', 'PG', FALSE),
('Mines', 2019, 'Aposta', 'PG', FALSE),
('Dragon Hatch', 'Aposta', 'PG', FALSE),
('Fortune Mouse', 2021, 'Aposta', 'PG', FALSE),
('Baccarat', 2020, 'Aposta', 'Pragmatic', FALSE),
('Back Bo', 2020, 'Aposta', 'Pragmatic', FALSE),
('Aviator', 2019, 'Aposta', 'Pragmatic', FALSE),
('Gold Party', 2022, 'Aposta', 'PG', FALSE),
('Pokemon Go', 2017, 'Aventura', 'Niantic', FALSE),
('Nebulos.io', 2017, 'Jogo eletrônico casual', 'Namazu Studios', TRUE),
('Pipa Combate', 2015, 'Jogo eletrônico casual', TRUE),
('BitLife', 2022, 'Jogo eletrônico casual', 'Good Games Studios', FALSE),
('Avakin Life', 2019, 'Jogo eletrônico casual', TRUE),
('Zombs.io', 2017, 'Jogo eletrônico casual', FALSE),
('Clash Royale', 2016, 'Jogo eletrônico casual', 'Supercell',FALSE),
('Clash of Clans', 2016, 'Jogo eletrônico casual', 'Supercell', FALSE),
('Payday 2', 2013, 'Ação', 'Overkill Software', FALSE),
('Payday 3', 2023, 'Ação', 'Overkill Software', FALSE),
('Payday: The Heist', 2011, 'Ação', 'Overkill Software', FALSE),
('Farcry', 2004, 'Aventura', 'Crytek', FALSE),
('Farcry 2', 2008, 'Aventura', 'Crytek', FALSE),
('Farcry 3', 2012, 'Aventura', 'Ubisoft Montreal', FALSE),
('Farcry 4', 2014, 'Aventura', 'Ubisoft Montreal', FALSE),
('Farcry 5', 2018, 'Aventura', 'Ubisoft Montreal', FALSE),
('Farcry 6', 2021, 'Aventura', 'Ubisoft', FALSE),
('Red Dead Redemption', 2010, 'Ação', 'Rockstar', FALSE),
('Red Dead Redemption 2', 2018, 'Ação', 'Rockstar', FALSE),
('Friday the 13th: The Game', 2017, 'Terror', 'Fonic', FALSE),
('Need For Speed', 1994, 'Corrida automóvel', 'Pioneer Production', FALSE)